name: Build latest docs

on:
  push:
    branches:
      - master

jobs:
    
  build_docs:
    name: build latest docs
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        pip install sphinx
        pip install sphinx-rtd-theme
    - name: Build sphinx documentation
      run: |
        make html
    - name: Install ssh-key in agent
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_DEPLOYMENT }}
      - name: Rsync deploy
        run: |
          rsync -av -e "ssh -o StrictHostKeyChecking=no" build/html/ kuben@172.104.246.236:/home/kuben/services/web/website/cpsign/docs/latest/
    
